[harvest]
sources = ["toml"]

[deposit]
target = "invenio_rdm"

[deposit.invenio_rdm]
site_url = "https://zenodo.org"
access_right = "open"
record_id = "13168127"

[postprocess]
execute = [ "config_record_id" ]
