# SPDX-FileCopyrightText: 2024 German Aerospace Center (DLR)
#
# SPDX-License-Identifier: CC0-1.0

# SPDX-FileContributor: Michael Meinel
# SPDX-FileContributor: Michael Fritzsche

name: Software publication on Zenodo Sandbox

on:
  push:
    tags:
      - "*"

jobs:
  hermes-plugin-python:
    name: HERMES-PLUGIN-PYTHON
    runs-on: ubuntu-latest
    permissions:
      contents: read # We will only read content from the repo
      # pull-requests: write # Postprocessing should be able to create a pull request with changes
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: pip install .
      - run: git archive --format zip HEAD src > hermes-plugin-python.zip
      - run: hermes harvest
      - run: hermes process
      - run: hermes curate
      - run: hermes deposit --auth-token ${{ secrets.ZENODO_SANDBOX }} --file hermes-plugin-python.zip --file README.md
